"""Deterministic, bounded follow-up windows within already discovered source files."""

from collections.abc import Sequence
from dataclasses import dataclass

from .models import ActionCandidate, ReadSnippetArgs
from .repository import MAX_CANDIDATES, SourceFile

FOLLOWUP_LINES = 9
EXPANSION_ALGORITHM = "adjacent-lines-v1"


def validate_max_followups(value: int) -> None:
    """Require an explicit bounded integer; zero preserves the fixed frontier."""
    if isinstance(value, bool) or not isinstance(value, int) or not 0 <= value <= MAX_CANDIDATES:
        raise ValueError(
            f"Follow-up candidate budget must be an integer from 0 to {MAX_CANDIDATES}."
        )


@dataclass(frozen=True)
class FollowupCandidate:
    candidate: ActionCandidate
    parent_candidate_id: str
    parent_observation_id: str
    direction: str

    def to_dict(self) -> dict:
        return {
            "candidate_id": self.candidate.id,
            "parent_candidate_id": self.parent_candidate_id,
            "parent_observation_id": self.parent_observation_id,
            "direction": self.direction,
        }


def _span_key(args: ReadSnippetArgs) -> tuple:
    return (args.path, args.expected_sha256, args.start_line, args.end_line, args.max_chars)


class FollowupFrontier:
    """Derive same-file windows without source reads, rescans, or policy-created actions.

    IDs are deterministic within one arm. Different exploration orders can assign
    different IDs to the same span, so comparisons must use semantic action identities.
    """

    def __init__(self, initial_candidates: Sequence[ActionCandidate], max_followups: int = 0):
        validate_max_followups(max_followups)
        initial = tuple(initial_candidates)
        if len(initial) > MAX_CANDIDATES:
            raise ValueError("Initial candidate frontier exceeds the candidate limit.")
        self._known = {candidate.id: candidate for candidate in initial}
        if len(self._known) != len(initial):
            raise ValueError("Initial candidate IDs must be unique.")
        self.max_followups = max_followups
        self.lineage: list[FollowupCandidate] = []
        self._initial_count = len(initial)
        self._next_id = len(initial) + 1
        self._considered_spans = {_span_key(candidate.args) for candidate in initial}
        self._processed_parents: set[str] = set()
        self._suppressed = 0
        self._candidate_suppressed = 0
        self._followup_suppressed = 0

    def expand(
        self, parent: ActionCandidate, source: SourceFile, observation_id: str
    ) -> tuple[FollowupCandidate, ...]:
        """Return new neighbors of one successfully read, registered source span."""
        if (
            self.max_followups == 0
            or source.sha256 != parent.args.expected_sha256
            or self._known.get(parent.id) != parent
            or parent.kind != "read_snippet"
            or parent.id in self._processed_parents
        ):
            return ()
        lines = source.text.splitlines(keepends=True)
        args = parent.args
        if args.start_line < 1 or args.end_line < args.start_line or args.end_line > len(lines):
            return ()
        self._processed_parents.add(parent.id)
        proposals = (
            ("before", max(1, args.start_line - FOLLOWUP_LINES), args.start_line - 1),
            ("after", args.end_line + 1, min(len(lines), args.end_line + FOLLOWUP_LINES)),
        )
        added = []
        for direction, start_line, end_line in proposals:
            if start_line > end_line:
                continue
            followup_args = ReadSnippetArgs(
                args.path, start_line, end_line, args.expected_sha256, args.max_chars
            )
            key = _span_key(followup_args)
            if key in self._considered_spans:
                continue
            self._considered_spans.add(key)
            candidate_limit = len(self._known) >= MAX_CANDIDATES
            followup_limit = len(self.lineage) >= self.max_followups
            if candidate_limit or followup_limit:
                self._suppressed += 1
                self._candidate_suppressed += int(candidate_limit)
                self._followup_suppressed += int(followup_limit)
                continue
            candidate_id = f"c{self._next_id:04}"
            while candidate_id in self._known:
                self._next_id += 1
                candidate_id = f"c{self._next_id:04}"
            self._next_id += 1
            candidate = ActionCandidate(
                candidate_id,
                "read_snippet",
                followup_args,
                max(0, parent.score - 1),
                (
                    f"Adjacent {direction} candidate {parent.id} in the same source snapshot",
                    f"At most {FOLLOWUP_LINES} lines; generated by {EXPANSION_ALGORITHM}",
                ),
                "".join(lines[start_line - 1 : end_line])[:240],
            )
            derived = FollowupCandidate(candidate, parent.id, observation_id, direction)
            self._known[candidate_id] = candidate
            self.lineage.append(derived)
            added.append(derived)
        return tuple(added)

    def describe(self) -> dict:
        """Expose capacity and actual suppression independently of source coverage."""
        return {
            "enabled": self.max_followups > 0,
            "algorithm": EXPANSION_ALGORITHM,
            "window_lines": FOLLOWUP_LINES,
            "max_followups": self.max_followups,
            "initial_candidates": self._initial_count,
            "generated_candidates": len(self.lineage),
            "suppressed_proposals": self._suppressed,
            "candidate_limit_reached": len(self._known) >= MAX_CANDIDATES,
            "followup_limit_reached": self.max_followups > 0
            and len(self.lineage) >= self.max_followups,
            "candidate_limit_suppressed_proposals": self._candidate_suppressed,
            "followup_limit_suppressed_proposals": self._followup_suppressed,
        }
